# $schema:https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  devcontainer:
    build: {}
    volumes:
      - ~/.docker_bash_history:/root/.ash_history
      - ~/.docker_bash_history:/home/app/.ash_history
      - .:/project
      - uv_cache:/home/app/.cache/uv
    ports:
      - "8123:8123"

volumes:
  uv_cache:
