services:
  devcontainer:
    build: {}
    volumes:
      - ~/.docker_bash_history:/root/.ash_history
      - ~/.docker_bash_history:/home/app/.ash_history
      - .:/project
    ports:
      - "8123:8123"
