#:schema https://json.schemastore.org/pyproject.json

[project]
name = "ha-proton-drive"
version = "0"
requires-python = ">=3.14.2"
dependencies = [
  "aiofiles>=25.1.0",
  "cachetools>=7.1.4",
  "cachetools-async>=0.0.5",
]

[dependency-groups]
dev = ["ruff==0.15.22", "tombi==1.2.4", "ty==0.0.62"]
docker = ["aiohasupervisor==0.6.0"]
hass = ["homeassistant==2026.4.0"]

[tool.ruff]
target-version = "py314"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed
  # conflicting rules
  "D203",
  "D212",
  "COM812",
  # they are useful
  "FIX001",
  "FIX002",
  "TD001",
  "TD002",
  "TD003",
]

[tool.ruff.lint.per-file-ignores]
"scripts/*.py" = ["T201"]

[tool.setuptools]
packages = ["custom_components"]

[tool.uv]
package = false
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
name = "hass-musl"
url = "https://wheels.home-assistant.io/musllinux-index/"
