# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: LouisBrunner/.github/.github/workflows/lint-all.yml@main
    permissions:
      actions: read
      contents: read
      statuses: write
      pull-requests: write

  vet:
    name: Vet
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/home-assistant/homeassistant-base:2026.05.0
      options: --user root
    steps:
      - name: Install dependencies
        run: apk add --no-cache git make

      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      # FIXME: for some reason the hash changes everyday for the same version
      - name: Refresh multidict hashes
        run: uv lock --upgrade-package multidict

      - name: Install dependencies
        run: make setup

      - name: Vet
        run: make vet

  manifest-sync:
    name: Manifest sync
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Set up Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
        with:
          version: 2.5.0

      - name: Check manifest sync
        run: |
          make manifest-sync
          if ! git diff --exit-code custom_components/proton_drive/manifest.json; then
            echo "manifest.json is out of sync, run 'make manifest-sync' to fix"
            exit 1
          fi
