# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  draft:
    name: Draft release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get version
        id: ver
        run: echo "version=$(jq -r '.version' custom_components/proton_drive/manifest.json)" >> "$GITHUB_OUTPUT"

      - name: Create draft release
        uses: LouisBrunner/.github/.github/actions/draft-release@main
        with:
          version: ${{ steps.ver.outputs.version }}
